server:
  port: 8761

spring:
  application:
    name: discovery
  security:
    user:
      name: admin
      password: admin

# eureka 가 포함되면 eureka server 도 등록되므로 해제한다.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://${spring.security.user.name}:${spring.security.user.password}@discovery:8761/eureka}

  server:
    peer-node-read-timeout-ms: 10000
